Test Case 1 Input:
"51 2 3 4 5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 2 Input:
"51 2 3 4 five"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 3 Input:
"5""1 2 3 4 5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 4 Input:
"5""1" "2" "3" "4" "5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 5 Input:
"5" "1 2 3 4 5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 6 Input:
"5" "1" "2" "3" "4" "5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 7 Input:
"5.5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 8 Input:
"5.5""1 2 3 4 5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 9 Input:
"5\n1 2 3 4 5"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 10 Input:
"abc"
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 11 Input:
"abc"1 2 3 4 5
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 12 Input:
"five"1 2 3 4 5
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 13 Input:
-(expected InputMismatchException)
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 14 Input:
-1
Error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:6)
Test Case 15 Input:
-10
Error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:6)
Test Case 16 Input:
-2
Error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:6)
Test Case 17 Input:
-5
Error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:6)
Test Case 18 Input:
-51 2 3 4 5
Error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:6)
Test Case 19 Input:
0
Output:
0
Test Case 20 Input:
1
Output:
0
Test Case 21 Input:
1.5
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 22 Input:
1.51 2 3
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 23 Input:
1.51 2 3 4 5
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 24 Input:
10
Output:
9
Test Case 25 Input:
100
Output:
18
Test Case 26 Input:
12
Output:
9
Test Case 27 Input:
21 2 3
Output:
1
Test Case 28 Input:
21 2 3 4
Output:
1
Test Case 29 Input:
21 2 3 4
Output:
1
Test Case 30 Input:
21 a 3
Output:
1
Test Case 31 Input:
2.51 2 3
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 32 Input:
3123
Output:
2
Test Case 33 Input:
31 2 "abc"
Output:
2
Test Case 34 Input:
31 2 3
Output:
2
Test Case 35 Input:
31 2 3 4
Output:
2
Test Case 36 Input:
31 2 3 a
Output:
2
Test Case 37 Input:
31 2 a
Output:
2
Test Case 38 Input:
31 2 aTest Case Input:41 2 3 bTest Case Input:21 2 3 4
Output:
2
Test Case 39 Input:
31 2 b
Output:
2
Test Case 40 Input:
31 2 null
Output:
2
Test Case 41 Input:
31 2 three
Output:
2
Test Case 42 Input:
31 a 3
Output:
2
Test Case 43 Input:
31 a 3Test Case Input:41 2 3 bTest Case Input:21 2 3
Output:
2
Test Case 44 Input:
31 null 3
Output:
2
Test Case 45 Input:
3.14
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 46 Input:
3.51 2 3
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 47 Input:
41 2 3 -4
Output:
3
Test Case 48 Input:
41 2 3 b
Output:
3
Test Case 49 Input:
43527
Output:
3
Test Case 50 Input:
4.51 2 3 4
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 51 Input:
512345
Output:
4
Test Case 52 Input:
51 "2" 3 4 5
Output:
4
Test Case 53 Input:
51 2 3 4 "5"
Output:
4
Test Case 54 Input:
51 2 3 4 "five"
Output:
4
Test Case 55 Input:
51 2 3 4 5
Output:
4
Test Case 56 Input:
51 2 3 4 5 6
Output:
4
Test Case 57 Input:
51 2 3 4 a
Output:
4
Test Case 58 Input:
51 2 3 4 five
Output:
4
Test Case 59 Input:
51 2 3 a 5
Output:
4
Test Case 60 Input:
51 2 3 b
Output:
4
Test Case 61 Input:
51 2 3 b 5
Output:
4
Test Case 62 Input:
51 2 3 four 5
Output:
4
Test Case 63 Input:
51 2 a 4 5
Output:
4
Test Case 64 Input:
51 2 three 4 5
Output:
4
Test Case 65 Input:
51 a 3 4 5
Output:
4
Test Case 66 Input:
51 two 3 4 5
Output:
4
Test Case 67 Input:
52 4 6 8 10
Output:
4
Test Case 68 Input:
53 2 5 4 1
Output:
4
Test Case 69 Input:
55 4 3 2 1
Output:
4
Test Case 70 Input:
5.51 2 3 4 5
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 71 Input:
71 3 5 7 9 11 13
Output:
6
Test Case 72 Input:
Test Case Input:Test Case Input:Test Case Input:0abc-10
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 73 Input:
abc
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 74 Input:
abc1 2 3 4 5
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 75 Input:
null
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
Test Case 76 Input:
xyz
Error:
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
	at Main.main(Main.java:5)
